{
 "title": "Training finished Exercise 1 dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Free heap of apps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(app, server) (avg_over_time(jvm_memory_max_bytes{area=\"heap\", job=\"axon-app\"}[5m])) - sum by(app, server) (jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "{{app}} {{ server }}"
    }
   ]
  },
  {
   "title": "Free heap of Axon Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(axonserver) (jvm_memory_max_bytes{area=\"heap\", job=\"axon-server\"}) - sum by(axonserver) (jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "{{axonserver}}"
    }
   ]
  },
  {
   "title": "Event processor handler duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(processorName) (eventProcessor_successTimer_seconds)",
     "legendFormat": "{{axonserver}}"
    }
   ]
  },
  {
   "title": "Event processor latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(processorName, app) (eventProcessor_latency)",
     "legendFormat": "{{app}} {{processorName}}"
    }
   ]
  },
  {
   "title": "CommandBus rate",
   "type": "timeseries",
   "description": "CommandBus message rate per minute, per application",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(app) (rate(commandBus_ingestedCounter_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CommandBus Errors",
   "type": "timeseries",
   "description": "CommandBus message rate per minute, per application",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum by(payloadType) (rate(commandBus_failureCounter_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command handler duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(payloadType) (commandBus_allTimer_seconds{quantile=\"0.95\"})",
     "legendFormat": "{{axonserver}}"
    }
   ]
  },
  {
   "title": "CommandBus capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "sum by(app) (commandBus_capacity)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query rate",
   "type": "timeseries",
   "description": "CommandBus message rate per minute, per application",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(app) (rate(queryBus_ingestedCounter_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QueryBus Errors",
   "type": "timeseries",
   "description": "CommandBus message rate per minute, per application",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "sum by(payloadType) (rate(commandBus_failureCounter_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query handler duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(payloadType) (queryBus_allTimer_seconds)",
     "legendFormat": "{{axonserver}}"
    }
   ]
  },
  {
   "title": "QueryBus capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "sum by(app) (queryBus_capacity)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}