@startuml

participant "AxonServer" as as
participant "AxonServerCommandBus" as ascb
queue Executor as e
participant "LocalSegment" as ls

as -> ascb: Command
ascb -> e: CommandProcessingTask
e -> ls: Command
ascb <-- ls: CommandResult
as <-- ascb: CommandResult

@enduml
