@startuml

participant "A: \nCaller" as ac
participant "A: \nAxonServerCommandBus" as ab
participant "\nAxonServer" as asee
participant "\nB: AxonServerCommandBus" as bb
queue "B: \nExecutor" as be
participant "B: \nSimpleCommandBus" as blb
participant "B: \nHandler" as bh


ac -> ab: Command
ab -> asee: Command
asee -> bb: Command
bb -> be: CommandProcessingTask
be -> blb: Command
blb -> bh: Command
blb <-- bh: CommandResult
bb <-- blb: CommandResult
asee <-- bb: CommandResult
ac <-- asee: CommandResult




@enduml
