@startuml

participant "AxonServer" as asee
participant "CommandBus" as cb
participant "EventBus" as eb
participant EventProcessor as e
participant EventHandler as eh

asee -> cb: Command
cb -> eb: Publish event
eb -> asee: Store event
cb --> asee: Command Result
asee -> e: Event
e -> e: Put in Stream
e -> eh: Handle when at position

@enduml
