@startuml

participant "Participant" as p

participant "Auctions \nService" as auctions
participant "Auctions \nQuery Service" as auctionsq
participant "Object \nRegistry Service" as or
participant "Participant \nService" as ps


== Registration ==
p -> ps: Registers
ps -> ps: EmailUniquePm checks \nif email is unique
p -> or: Registers items for possible auctions

== Auction ==
p -> auctions: Starts auction for item
auctions -> auctionsq: Events for projection
auctionsq -> p: Subscription query updates for auctions

p -> auctions: Can bid on item
auctions -> or: Event that auction ended with winner
or -> ps: Saga: Deduct balance from buyer
or -> ps: Saga: Increase balance of seller
or -> or: Saga: Change item's owner in registry
or -> p: Subscription query updates for ownership
ps -> p: Subscription query updates for balance

@enduml
