{
 "title": "Axon Server Cluster Overview Public Preview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Status",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "up{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Error/Warnings",
   "type": "timeseries",
   "description": "Shows count of errors and warnings in Axon Server",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (level) (increase(logback_events_total{level=\"warn\",job=\"$job\"}[1m]))",
     "legendFormat": "Warnings"
    },
    {
     "expr": "sum by (level) (increase(logback_events_total{level=\"error\",job=\"$job\"}[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Unhealthy Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"$job\"})-count(system_cpu_count{job=\"$job\"})",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "Errors in time range",
   "type": "stat",
   "description": "Shows count of errors of  Axon Server in the given time range",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(logback_events_total{level=\"error\",job=\"$job\"}[$__range])))",
     "legendFormat": "{{instancec}}"
    }
   ]
  },
  {
   "title": "CPU% Basic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"$job\"}*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Events last hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(axon_event_count_total[1h])))\n# Context may be replicated or just in one node, therefore use the \"most progressed\" node per context. \n# Sum these values to get the amount of events stored across all contexts and nodes.",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Commands last hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(axon_command_count_total[1h])))",
     "legendFormat": "{{context}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Number of Queries last hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(axon_query_count_total[1h])))",
     "legendFormat": "{{context}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Fullest Volume",
   "type": "gauge",
   "description": "Filled percentage of the most-full volume used by AxonServer of all instances",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((disk_total_bytes{job=\"$job\"}-disk_free_bytes{job=\"$job\"})/disk_total_bytes {job=\"$job\"})",
     "legendFormat": "{{path}}\\n{{instance}}"
    }
   ]
  },
  {
   "title": "Rate of Events [5m]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "evt/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(rate(axon_event_count_total[5m])) by (context))\n# Context may be replicated or just in one node, therefore use the \"most progressed\" node per context. \n# Sum these values to get the amount of events stored across all contexts and nodes.",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Commands [5m]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cmd/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(axon_command_count_total[5m]))",
     "legendFormat": "{{context}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Rateof Queries [5m]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "qry/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(axon_query_count_total[5m]))",
     "legendFormat": "{{context}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Overflow Queues",
   "type": "stat",
   "description": "Commands and Queries waiting in queues to be processed by applications.\nThis Value should always be zero",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(axon_ApplicationQueryQueue_size)",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum(axon_ApplicationCommandQueue_size)",
     "legendFormat": "Commands"
    }
   ]
  },
  {
   "title": "Number of Snapshots last hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(axon_snapshot_count_total[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token differences",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(axonserver, context) (rate(axon_event_lastToken{job=\"axon-server\"}[1m])) - min by(axonserver, context) (rate(axon_event_lastToken{job=\"axon-server\"}[1m]))",
     "legendFormat": "{{axonserver}} {{context}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 26, "w": 7, "x": 0, "y": 33 },
   "options": {
    "content": "# Network related statistics\n\nSome of the GRPC requests are inteded to run for a long time, even months. \nThat's the reason why some calls will show large latencies or durations.\n\nYou will observe a spike of high-latency requests appearing when an AS node is stopped.\nWhen a node stops, connections that might have been upheld for weeks are terminated.\nThis leads to the metric of their \"latency\" to be recorded at that moment.\n\n\n## Command E2E Duration\nThis visualization depics the duration for a command to be delivered, executed by the client application and it's result reported back.\nThis in particular includes the duration your command handler takes to process the command.\n\n## GRPC Method Duration Heatmap\nHeatmap of the duration of all grpc methods over time.\nIt is normal to see few entries in all buckets of afore-mentioned reasons.\nAlso, horizontal lines appear commonly at 6ms and 250ms.\nChanges in color wrt to the time axis are things to look into, if the cause is not related to changes in infrastructure.\n\n## p95 GRPC Method Duration\n95th percentile of GRPC method durations.\nThis filters out large spikes, like the ones occuring when an application disconnects that has been streaming events for days.\nHowever, since there are long-running grpc calls (see the histogram for their distribution), this metric might hive a false sense of the \"common\" duration, a call takes.\n\n## GRPC Method Duration [5 min avg]\n5 minute averages **by method** for grpc calls.\nThis is helpful to track down unexpected behavior.\nIf a long-running grpc method call ends, it will show up as a dot here.\nIf that is unexpected, this panel might help you identify the affected component.\nAn example for this is that a client application unexpectedly disconnected and you should check your logs.\n"
   }
  },
  {
   "title": "Command E2E Duration",
   "type": "timeseries",
   "description": "Registers the duration of a command in the registry.\nMeaning measures time that the command handler takes to execute.",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (request) (irate(axon_commands_seconds_sum[5m]))/ sum by (request) (irate(axon_commands_seconds_count[5m]) )",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "GRPC Method Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 43 },
   "targets": [
    {
     "expr": "sum by (le) ( rate(grpc_io_server_server_latency_cumulative_bucket[5m]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 GRPC Method Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_server_latency_cumulative_bucket{job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GRPC Method Duration [5 min avg]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(grpc_io_client_roundtrip_latency_cumulative_sum{job=~\"$job\"}[1m])/rate(grpc_io_client_roundtrip_latency_cumulative_count{job=~\"$job\"}[1m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall request rate by method",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_server_latency_cumulative_count[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}