{
 "title": "Training finished Exercise 1 dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Free heap of apps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(app, server) (avg_over_time(jvm_memory_max_bytes{area=\"heap\", job=\"axon-app\"}[5m])) - sum by(app, server) (jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "{{app}} {{ server }}"
    }
   ]
  },
  {
   "title": "Free heap of Axon Server",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(axonserver) (jvm_memory_max_bytes{area=\"heap\", job=\"axon-server\"}) - sum by(axonserver) (jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "{{axonserver}}"
    }
   ]
  },
  {
   "title": "Event processor handler duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(processorName) (eventProcessor_successTimer_seconds)",
     "legendFormat": "{{axonserver}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(eventProcessor_successTimer_seconds[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event processor latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(processorName, app) (avg_over_time(eventProcessor_latency[1m]))",
     "legendFormat": "{{app}} {{processorName}}"
    }
   ]
  },
  {
   "title": "CommandBus rate",
   "type": "timeseries",
   "description": "CommandBus message rate per minute, per application",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(app) (rate(commandBus_ingestedCounter_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CommandBus Errors",
   "type": "timeseries",
   "description": "CommandBus message rate per minute, per application",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum by(payloadType) (rate(commandBus_failureCounter_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command handler duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(payloadType) (commandBus_allTimer_seconds{quantile=\"0.95\"})",
     "legendFormat": "{{axonserver}}"
    }
   ]
  },
  {
   "title": "CommandBus capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(app) (commandBus_capacity) / sum by(app) (commandBus_capacity_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query rate",
   "type": "timeseries",
   "description": "CommandBus message rate per minute, per application",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(app) (rate(queryBus_ingestedCounter_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QueryBus Errors",
   "type": "timeseries",
   "description": "CommandBus message rate per minute, per application",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "sum by(payloadType) (rate(commandBus_failureCounter_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query handler duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(payloadType) (queryBus_allTimer_seconds)",
     "legendFormat": "{{axonserver}}"
    }
   ]
  },
  {
   "title": "QueryBus capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(app) (queryBus_capacity) / sum by(app) (queryBus_capacity_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command Bus Latency (AS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(request) (rate(axon_commands_seconds_sum[1m])) / sum by(request) (rate(axon_commands_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command Bus Latency by target (AS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum by(target) (rate(axon_commands_seconds_sum[1m])) / sum by(target) (rate(axon_commands_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Bus Latency (AS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(request) (rate(axon_queries_seconds_sum[1m])) / sum by(request) (rate(axon_queries_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Bus Latency by target (AS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "sum by(target) (rate(axon_queries_seconds_sum[1m])) / sum by(target) (rate(axon_queries_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free disk space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "disk_free_bytes{job=\"axon-server\"}",
     "legendFormat": "{{axonserver}} {{path}}"
    }
   ]
  },
  {
   "title": "AS messages active",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "targets": [
    { "expr": "sum(axon_commands_active)", "legendFormat": "Commands" },
    { "expr": "sum(axon_queries_active)", "legendFormat": "Queries" }
   ]
  },
  {
   "title": "Database connections available",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum by(app) (hikaricp_connections_max{job=\"axon-app\"}) - sum by(app) (hikaricp_connections_active{job=\"axon-app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segments claimed per processor",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(app, eventProcessor) (eventProcessor_segments_claimed{job=\"axon-app\"})",
     "legendFormat": "{{eventProcessor}} {{app}}"
    }
   ]
  }
 ]
}